# -*- coding: utf-8 -*-
"""Abayaty_UI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yl5ihIEmF0XHCjjhxBceIxQJC-nrZp8G
"""

import streamlit as st
import pandas as pd
import numpy as np
import requests
from PIL import Image
from io import BytesIO
from sklearn.metrics.pairwise import cosine_similarity
import concurrent.futures
import json
from datetime import datetime

# -------------------------------------
# Load Data with Caching
# -------------------------------------
@st.cache_data(show_spinner=False)
def load_all_data():
    df = pd.read_csv("Abayas_alldata.csv")
    emb = np.load("combined_embeddings.npy")

    # Clean price
    df['p_base_price'] = (
        df['p_base_price']
        .astype(str)
        .str.replace('$', '', regex=False)
        .str.replace(',', '', regex=False)
        .astype(float)
    )
    return df, emb

df, emb = load_all_data()

# -------------------------------------
# Improved image loading with better error handling
# -------------------------------------
@st.cache_data(show_spinner=False, ttl=3600)
def load_single_image(url):
    try:
        r = requests.get(url, timeout=10)  # Increased timeout
        if r.status_code == 200:
            img = Image.open(BytesIO(r.content))
            # Optimize image size for faster loading
            img.thumbnail((500, 500), Image.Resampling.LANCZOS)
            return url, img.convert("RGB")
        return url, None
    except Exception as e:
        print(f"Error loading image {url}: {e}")
        return url, None

@st.cache_data(show_spinner=False, ttl=300)
def preload_images_parallel(url_list):
    images = {}
    # Load images in smaller batches for better stability
    batch_size = 8
    for i in range(0, len(url_list), batch_size):
        batch_urls = url_list[i:i + batch_size]
        with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
            future_to_url = {executor.submit(load_single_image, url): url for url in batch_urls}
            for future in concurrent.futures.as_completed(future_to_url):
                url, img = future.result()
                images[url] = img
    return images

# -------------------------------------
# Precompute similarities for faster recommendations
# -------------------------------------
@st.cache_data(show_spinner=False)
def find_similar_cached(_emb, idx, top_n=8):
    query = _emb[idx].reshape(1, -1)
    sims = cosine_similarity(_emb, query).flatten()
    indices = sims.argsort()[::-1][1:top_n+1]
    return indices

def find_similar(idx, top_n=8):
    indices = find_similar_cached(emb, idx, top_n)
    return df.iloc[indices]

# -------------------------------------
# Feedback System
# -------------------------------------
def save_feedback(product_id, rating, comment="", recommendation_id=None):
    """Save user feedback to session state and local file"""
    feedback = {
        "timestamp": datetime.now().isoformat(),
        "product_id": int(product_id),
        "rating": rating,
        "comment": comment,
        "recommendation_id": recommendation_id
    }

    # Save to session state
    if "user_feedback" not in st.session_state:
        st.session_state.user_feedback = []

    st.session_state.user_feedback.append(feedback)

    # Save to file (for persistence)
    try:
        with open("user_feedback.json", "a") as f:
            f.write(json.dumps(feedback) + "\n")
    except:
        pass

    return feedback

def get_feedback_stats():
    """Get statistics about user feedback"""
    if "user_feedback" not in st.session_state:
        return {"total_ratings": 0, "average_rating": 0, "total_comments": 0}

    feedbacks = st.session_state.user_feedback
    if not feedbacks:
        return {"total_ratings": 0, "average_rating": 0, "total_comments": 0}

    ratings = [f["rating"] for f in feedbacks if "rating" in f]
    comments = [f for f in feedbacks if f.get("comment")]

    return {
        "total_ratings": len(ratings),
        "average_rating": sum(ratings) / len(ratings) if ratings else 0,
        "total_comments": len(comments)
    }

# -------------------------------------
# Sidebar
# -------------------------------------
st.sidebar.title("Controls")

if "current_search" not in st.session_state:
    st.session_state.current_search = ""
if "current_category" not in st.session_state:
    st.session_state.current_category = "All"
if "page_history" not in st.session_state:
    st.session_state.page_history = []

search_name = st.sidebar.text_input("Search product name", value=st.session_state.current_search)
categories = ["All"] + sorted(df['category'].dropna().unique().tolist()) if 'category' in df.columns else ["All"]
selected_category = st.sidebar.selectbox("Category", categories, index=categories.index(st.session_state.current_category))

products_per_page = st.sidebar.selectbox("Products per page", [8, 12, 16, 20], index=2)

if search_name != st.session_state.current_search:
    st.session_state.current_search = search_name
    if st.session_state.page == "details":
        st.session_state.page_history.append(("home", None))
        st.session_state.page = "home"
        st.rerun()

if selected_category != st.session_state.current_category:
    st.session_state.current_category = selected_category
    if st.session_state.page == "details":
        st.session_state.page_history.append(("home", None))
        st.session_state.page = "home"
        st.rerun()

# Apply filters
filtered = df.copy()
if st.session_state.current_search:
    filtered = filtered[filtered["p_name"].str.contains(st.session_state.current_search, case=False, na=False)]
if st.session_state.current_category != "All":
    filtered = filtered[filtered["category"] == st.session_state.current_category]

if st.session_state.current_search and len(filtered) == 0:
    st.sidebar.warning(f"No products found for: '{st.session_state.current_search}'")

total = len(filtered)
pages = max(1, (total // products_per_page) + (1 if total % products_per_page else 0))
page = st.sidebar.number_input("Page", 1, pages, 1)
start = (page - 1) * products_per_page
page_data = filtered.iloc[start:start+products_per_page]

# Preload images with progress indication
if len(page_data) > 0:
    image_urls = page_data['p_img'].tolist()
    with st.spinner('🔄 Loading images...'):
        preloaded_images = preload_images_parallel(image_urls)
else:
    preloaded_images = {}

# -------------------------------------
# Feedback Analytics in Sidebar
# -------------------------------------
st.sidebar.write("---")
st.sidebar.subheader("📊 Feedback Analytics")

feedback_stats = get_feedback_stats()
st.sidebar.metric("Total Ratings", feedback_stats["total_ratings"])
st.sidebar.metric("Average Rating", f"{feedback_stats['average_rating']:.1f} ⭐")
st.sidebar.metric("Comments Received", feedback_stats["total_comments"])

if st.sidebar.button("View All Feedback"):
    if "user_feedback" in st.session_state and st.session_state.user_feedback:
        st.sidebar.write("### Recent Feedback")
        for i, feedback in enumerate(st.session_state.user_feedback[-5:]):
            st.sidebar.write(f"⭐ {feedback['rating']}/5 - {feedback.get('comment', 'No comment')}")
    else:
        st.sidebar.info("No feedback yet")

# -------------------------------------
# Session state
# -------------------------------------
if "page" not in st.session_state:
    st.session_state.page = "home"
if "selected_index" not in st.session_state:
    st.session_state.selected_index = None

# -------------------------------------
# Title - Improved CSS with smaller feedback sections
# -------------------------------------
st.markdown("""
<style>
.product-card {
    text-align: center;
    margin-bottom: 25px;
    padding: 0px;
}
.product-title {
    font-weight: bold;
    font-size: 14px;
    margin: 8px 0px 4px 0px;
    height: 40px;
    overflow: hidden;
}
.product-price {
    font-size: 16px;
    font-weight: bold;
    color: #8b5e3c;
    margin: 4px 0px 8px 0px;
}
.stButton>button {
    width: 100%;
    border-radius: 5px;
    margin-top: 5px;
    font-size: 12px;
    padding: 3px 6px;
}
.feedback-section {
    background-color: #f8f9fa;
    padding: 15px;
    border-radius: 10px;
    margin: 10px 0px;
}
.small-feedback {
    background-color: #f0f2f6;
    padding: 8px;
    border-radius: 6px;
    margin: 4px 0px;
    border-left: 3px solid #8b5e3c;
}
.small-slider {
    margin: 5px 0px;
}
.small-textarea {
    font-size: 12px;
    min-height: 50px;
    margin: 5px 0px;
}
.small-button {
    font-size: 11px;
    padding: 2px 8px;
    margin: 2px 0px;
}
.compact-expander .streamlit-expanderHeader {
    font-size: 12px;
    padding: 6px 8px;
}
</style>
""", unsafe_allow_html=True)

st.markdown("<h1 style='text-align:center;font-weight:bold;color:#8b5e3c;'>Abayaty 🖤</h1>", unsafe_allow_html=True)

# -------------------------------------
# Navigation functions - OPTIMIZED
# -------------------------------------
def navigate_to_page(page_name, selected_index=None):
    if st.session_state.page == "details":
        st.session_state.page_history.append((st.session_state.page, st.session_state.selected_index))

    st.session_state.page = page_name
    if selected_index is not None:
        st.session_state.selected_index = selected_index
    st.rerun()

def go_back():
    if st.session_state.page_history:
        previous_page, previous_index = st.session_state.page_history.pop()
        st.session_state.page = previous_page
        st.session_state.selected_index = previous_index
        st.rerun()
    else:
        st.session_state.page = "home"
        st.session_state.selected_index = None
        st.rerun()

# -------------------------------------
# HOME PAGE - Clean layout without boxes
# -------------------------------------
if st.session_state.page == "home":
    st.subheader("✨ Explore Our Collection")

    if st.session_state.current_search:
        st.write(f"**{len(filtered)}** products found for **'{st.session_state.current_search}'**")

    if len(page_data) == 0:
        st.info("No products found. Try adjusting your search filters.")
    else:
        cols = st.columns(4, gap="medium")

        for i, (_, row) in enumerate(page_data.iterrows()):
            with cols[i % 4]:
                img = preloaded_images.get(row['p_img'])
                if img:
                    st.image(img, use_column_width=True, output_format="JPEG")
                else:
                    st.info("📷")

                st.markdown(f'<div class="product-title">{row["p_name"][:45]}{"..." if len(row["p_name"]) > 45 else ""}</div>', unsafe_allow_html=True)
                st.markdown(f'<div class="product-price">${row["p_base_price"]:.2f}</div>', unsafe_allow_html=True)

                if st.button("View", key=f"view_{row.name}"):
                    navigate_to_page("details", row.name)

# -------------------------------------
# DETAILS PAGE - Improved with better image loading and compact feedback
# -------------------------------------
elif st.session_state.page == "details":
    idx = st.session_state.selected_index
    if idx is None or idx not in df.index:
        st.error("Product not found. Returning to home page.")
        navigate_to_page("home")
    else:
        product = df.loc[idx]

        st.subheader("Product Details")

        # Product image with better loading
        with st.spinner('🔄 Loading product image...'):
            product_img = load_single_image(product['p_img'])[1]

        if product_img:
            st.image(product_img, width=350, output_format="JPEG")
        else:
            st.info("📷")

        st.write(f"### {product['p_name']}")
        st.write(f"**Price:** ${product['p_base_price']:.2f}")

        if 'category' in df.columns and pd.notna(product['category']):
            st.write(f"**Category:** {product['category']}")

        if 'p_description' in df.columns and pd.notna(product['p_description']):
            with st.expander("Product Description"):
                st.write(product['p_description'])

        # -------------------------------------
        # PRODUCT FEEDBACK SECTION
        # -------------------------------------
        st.write("---")
        st.subheader("💬 Rate This Product")

        with st.container():
            st.markdown('<div class="feedback-section">', unsafe_allow_html=True)

            product_rating = st.slider(
                "How do you like this product?",
                1, 5, 3,
                key="product_rating"
            )

            product_comment = st.text_area(
                "Your comments (optional)",
                placeholder="What did you like or dislike?",
                key="product_comment",
                height=70
            )

            if st.button("Submit Rating", key="submit_product_rating"):
                save_feedback(idx, product_rating, product_comment)
                st.success("✅ Thank you for your feedback!")

            st.markdown('</div>', unsafe_allow_html=True)

        st.write("---")

        # Recommendations with improved image loading
        recs = find_similar(idx)
        st.subheader("You May Also Like")

        # Preload recommendation images
        rec_image_urls = recs['p_img'].tolist()
        with st.spinner('🔄 Loading recommendations...'):
            rec_preloaded_images = preload_images_parallel(rec_image_urls)

        rec_cols = st.columns(4, gap="medium")

        for j, (_, row) in enumerate(recs.iterrows()):
            with rec_cols[j % 4]:
                rec_img = rec_preloaded_images.get(row['p_img'])
                if rec_img:
                    st.image(rec_img, use_column_width=True, output_format="JPEG")
                else:
                    st.info("📷")

                st.markdown(f'<div class="product-title">{row["p_name"][:40]}{"..." if len(row["p_name"]) > 40 else ""}</div>', unsafe_allow_html=True)
                st.markdown(f'<div class="product-price">${row["p_base_price"]:.2f}</div>', unsafe_allow_html=True)

                # -------------------------------------
                # COMPACT RECOMMENDATION FEEDBACK
                # -------------------------------------
                with st.expander("💡 Quick Feedback", expanded=False):
                    st.markdown('<div class="small-feedback">', unsafe_allow_html=True)

                    st.write("**Helpful?**")
                    rec_rating = st.slider(
                        "Score", 1, 5, 3,
                        key=f"rec_rating_{row.name}"
                    )

                    rec_comment = st.text_area(
                        "Comment",
                        placeholder="Quick note...",
                        key=f"rec_comment_{row.name}",
                        height=50
                    )

                    if st.button("Submit", key=f"submit_rec_{row.name}"):
                        save_feedback(idx, rec_rating, rec_comment, row.name)
                        st.success("👍 Thanks!")

                    st.markdown('</div>', unsafe_allow_html=True)

                if st.button("View Product", key=f"rec_{row.name}"):
                    navigate_to_page("details", row.name)

        # -------------------------------------
        # COMPACT OVERALL FEEDBACK
        # -------------------------------------
        st.write("---")
        st.subheader("📝 Overall Feedback")

        with st.container():
            st.markdown('<div class="small-feedback">', unsafe_allow_html=True)

            overall_rating = st.slider(
                "Overall experience",
                1, 5, 3,
                key="overall_rating"
            )

            overall_comment = st.text_area(
                "Additional comments",
                placeholder="Your thoughts...",
                key="overall_comment",
                height=60
            )

            col1, col2 = st.columns(2)
            with col1:
                if st.button("Submit", key="submit_overall"):
                    save_feedback(idx, overall_rating, overall_comment, "overall")
                    st.success("🎉 Thank you!")
            with col2:
                if st.button("Skip", key="skip_overall"):
                    st.info("Feedback helps us improve!")

            st.markdown('</div>', unsafe_allow_html=True)

        # Navigation
        st.write("---")
        col1, col2 = st.columns(2)
        with col1:
            if st.button("⬅ Back"):
                go_back()
        with col2:
            if st.button("🏠 Home"):
                st.session_state.page_history = []
                st.session_state.current_search = ""
                st.session_state.current_category = "All"
                navigate_to_page("home")
else:
    navigate_to_page("home")